name: Build Linux AMD64

on:
  push:
    branches: [ master ]

jobs:

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    timeout-minutes: 45

    steps:

    - name: Clone Repo
      uses: actions/checkout@v3

    - name: OS Packages
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential cmake git libcapstone-dev python3 time

    - name: Build Keystone
      run: |
        git clone https://github.com/EgeBalci/keystone
        mkdir keystone/build
        cd keystone/build
        ../make-lib.sh
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DLLVM_TARGETS_TO_BUILD="AArch64;X86" -G "Unix Makefiles" ..
        make -j8
        sudo make install
        sudo ldconfig

    - name: Build SGN Linux
      run: |
        GOOS=linux CGO_ENABLED=1 GOARCH=amd64 go build -ldflags="-s -w" -trimpath -o sgn_linux-amd64

    - name: Test SGN
      run: |
        ./sgn_linux-amd64 -h

    - name: Build SGN Windows
      run: |
        GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CGO_LDFLAGS="-lkeystone -L`pwd`keystone/build/lib/" CXX=x86_64-w64-mingw32-g++ CC=x86_64-w64-mingw32-gcc go build -ldflags="-s -w" -trimpath -o sgn_windows-amd64.exe
