name: Build MacOS

on:
  push:
    branches: [ master ]

jobs:

  build:
    name: Build MacOS
    runs-on: macos-latest
    timeout-minutes: 45

    steps:

    - name: Clone Repo
      uses: actions/checkout@v3

    - name: Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: '1.18.5'

    - name: OS Packages
      run: |
        brew install cmake git capstone python3

    - name: Build Keystone
      run: |
        git clone https://github.com/EgeBalci/keystone
        mkdir keystone/build
        cd keystone/build
        ../make-lib.sh
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -DLLVM_TARGETS_TO_BUILD="AArch64;X86" -G "Unix Makefiles" ..
        make -j8
        sudo make install

    - name: Build SGN AMD64
      run: |
        GOOS=darwin CGO_ENABLED=1 CGO_LDFLAGS="-lkeystone -L/usr/lib/" go build -ldflags="-s -w" -trimpath -o sgn_macos-amd64

    - name: MacOS Artifacts (AMD64)
      uses: actions/upload-artifact@v2
      with:
        name: macos-amd64
        path:  ./sgn_macos-amd64

    - name: Build SGN ARM64
      run: |    
        GOOS=darwin GOARCH=arm64 CGO_ENABLED=1 CGO_LDFLAGS="-lkeystone -L/usr/lib/" go build -ldflags="-s -w" -trimpath -o sgn_macos-arm64

    - name: MacOS Artifacts (ARM64)
      uses: actions/upload-artifact@v2
      with:
        name: macos-arm64
        path:  ./sgn_macos-arm64
